name: Pytest

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.6', '3.7', '3.8', '3.9.0-beta.5']
        isolated_backend_test: ['']
        isolated_validator_test: ['']
        include:
          # google pub/sub requires protobuf, and aws (moto) requires jsonschema
          - python_version: '3.8'
            isolated_backend_test: google
            isolated_validator_test: protobuf
          - python_version: '3.8'
            isolated_backend_test: aws
            isolated_validator_test: jsonschema
    steps:
      - id: setup
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - id: checkout
        name: Checkout PR
        uses: actions/checkout@v2

      - id: pytest
        name: Run Pytest
        run: make test
        env:
          GITHUB_CI: true
          ISOLATED_BACKEND_TEST: ${{ matrix.isolated_backend_test }}
          ISOLATED_VALIDATOR_TEST: ${{ matrix.isolated_validator_test }}
